package project276.group4.ui.Entity;

import project276.group4.domain.GameConstants;
import project276.group4.domain.entities.MovingGuardian;
import project276.group4.domain.entities.Player;
import project276.group4.domain.map.GameMap;
// import project276.group4.domain.types.DifficultyLevel; // removed unused import
import project276.group4.domain.types.GameOverReason;
import project276.group4.domain.types.Position;
import project276.group4.ui.DefaultGameSignals;
import project276.group4.ui.ResourceLoader;

import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;

import java.util.List;

/**
 * Manages all guardian enemies in the game.
 * Uses EntitySpawner to produce all spawn points, including guardian positions.
 * GuardianManager responsiblity:
 *  - Creates guardians from the provided spawn list
 *  - Moves them periodically
 *  - Updates positions
 *  - Detects collision with the player
 */
public class GuardianManager extends EntityManager<MovingGuardian> {

    private final Player player;
    private final GameMap map;
    private final DefaultGameSignals signals;

    private final List<Position> spawnPositions; // provided by EntitySpawner

    private int moveCounter = 0;

    /**
     * Creates a GuardianManager using spawn positions produced by EntitySpawner.
     *
     * @param root UI pane to hold guardian image nodes
     * @param player Player reference for tracking and collision
     * @param map Game map reference
     * @param signals Used to trigger game over events
     * @param guardianPositions Positions generated by EntitySpawner
     */
    public GuardianManager(
            Pane root,
            Player player,
            GameMap map,
            DefaultGameSignals signals,
            List<Position> guardianPositions) {
        super(root);
        this.player = player;
        this.map = map;
        this.signals = signals;
        this.spawnPositions = guardianPositions;
    }

    /**
     * Initializes guardians based on positions provided by EntitySpawner.
     */
    @Override
    public void initialize() {
        for (Position pos : spawnPositions) {
            MovingGuardian guardian = new MovingGuardian(
                pos,
                GameConstants.GUARDIAN_DEFAULT_VISION,
                GameConstants.GUARDIAN_DEFAULT_SPEED,
                GameConstants.GUARDIAN_DEFAULT_DAMAGE
            );
            ImageView view = createGuardianNode(pos);

            entities.add(guardian);
            entityNodes.add(view);
            root.getChildren().add(view);
        }
    }

    /**
     * Updates guardian movement, position, and checks collision with player.
     */
    @Override
    public void update() {
        moveCounter++;
        boolean shouldMove = moveCounter >= GameConstants.GUARDIAN_MOVE_DELAY_FRAMES;

        for (int i = 0; i < entities.size(); i++) {
            MovingGuardian guardian = entities.get(i);
            ImageView node = entityNodes.get(i);

            if (shouldMove) {
                guardian.performTurn(player, map);
            }

            // location
            node.setTranslateX(guardian.getPosition().getX() * GameConstants.TILE_SIZE);
            node.setTranslateY(guardian.getPosition().getY() * GameConstants.TILE_SIZE);

            // check collision with player
            if (guardian.getPosition().equals(player.getPosition())) {
                signals.onPlayerDamaged("guardian");
                signals.triggerGameOver(GameOverReason.GUARDIAN_CONTACT);
                return;
            }
        }
        if (shouldMove) moveCounter = 0;
    }

    /**
     * Creates the visual ImageView for a guardian.
     */
    private ImageView createGuardianNode(Position pos) {
        ImageView imgView = ResourceLoader.loadImageView("/assets/images/guardian.png", GameConstants.TILE_SIZE, GameConstants.TILE_SIZE);
        imgView.setTranslateX(pos.getX() * GameConstants.TILE_SIZE);
        imgView.setTranslateY(pos.getY() * GameConstants.TILE_SIZE);
        return imgView;
    }
}
